@startuml
'https://plantuml.com/sequence-diagram

autonumber

loop Actualizacion Colecciones (cada 1 hora)
    activate ColeccionScheduler
    ColeccionScheduler -> ColeccionService: actualizarColecciones()
    activate ColeccionService
    ColeccionService -> ColeccionRepository: findAll()
    activate ColeccionRepository
    loop Por cada fuente que haya traido
        ColeccionRepository --> ColeccionService: Set<Coleccion>
        ColeccionService -> Fuente: servicioPorTipoFuente(ColeccionService)
        activate Fuente
        Fuente -> ColeccionService: ColeccionService.pediAlServicioSegunEsteTipoFuente()
        ColeccionService -> ServicioFuente: getFuenteConHechosActualizados()
        activate ServicioFuente
        == Delay por usar comunicacion HTTP ==
        ServicioFuente --> ColeccionService: DTOHechosFuente
        deactivate ServicioFuente
        ColeccionService --> Fuente: void
        note right
            Vuelvo a la fuente porque la fuente había llamado al service
        end note
        Fuente --> ColeccionService: void
        note left
            Vuelvo al service porque el habia llamado a la fuente
        end note

    end
end


@enduml