@startuml
'https://plantuml.com/class-diagram

'CONTROLLERS
class HechoGlobalController {
    - HechoRepository hechosRepository
    + ResponseEntity<Set<Hecho>> getAll()
    + ResponseEntity<Set<Hecho>> getByTitulo(@PathVariable("titulo") String titulo)
    + ResponseEntity<Void> eliminarTodo()
}

class ColeccionHechoController {
    - HechoService hechoService
    + ResponseEntity<String> importar(@RequestParam("archivo") MultipartFile archivo)
    + ResponseEntity<Set<Hecho>> getByColeccion(@PathVariable String id)
}

'DAOS
interface IHechosDAO {
    Set<HechoValueObject> getAll(InputStream inputStream)
}

class DAOHechosCSV {
    + Set<HechoValueObject> getAll(InputStream inputStream)
    + HechoValueObject mapearDesdeCSV(HechoCSV fila)
}

class HechoCSV {
    - String titulo;
    - String descripcion;
    - String nombre;
    - String categoria;
    - float latitud;
    - float longitud;
    - String fecha;
}

'DTOS
class HechoValueObject {
    - String titulo
    - String descripcion
    - Categoria categoria
    - Ubicacion ubicacion
    - LocalDate fechaAcontecimiento
    + public boolean esIgualA(HechoValueObject unHecho)
}

'ENTITIES
class Categoria {
    - String nombre
    + boolean esIgualA(Categoria categoria)
}

class ColeccionHecho {
    - UUID id
    - LocalDate fechaCreacion
    - Set<Hecho> hechos
    + agregarHecho(Hecho hecho)
    + UUID getId()
    + Set<Hecho> getHechos
}

class Hecho {
    - ColeccionHecho coleccion;
    - String titulo;
    - String descripcion;
    - Categoria categoria;
    - Ubicacion ubicacion;
    - LocalDate fechaAcontecimiento
    - LocalDate fechaCarga;
    - Origen origen;
    - boolean eliminado;
    - boolean tieneContenidoMultimedia;
    - Set<String> etiquetas;
    + Hecho(HechoValueObject infoHecho, Origen origen, ColeccionHecho coleccion)
    + agregarEtiquetas(String ... etiquetas)
}

enum Origen {
    CARGAMANUAL
    PORCONTRIBUYENTE
    PORDATASET
}

class Ubicacion {
    - float longitud
    - float latitud
    + Ubicacion(float longitud, float latitud)
}

'REPOSITORIES
interface IHechoRepository {
    Set<Hecho> findAll()
    Set<Hecho> findAll(String coleccionID)
    void saveAll(UUID coleccionID, Set<Hecho> hechos)
    Optional<Set<Hecho>> buscarPorTitulo(String titulo)
    Optional<Set<Hecho>> findByColeccion(String idColeccion)
    void clear(String coleccionID)
    void clear()
}

class HechoRepository {
    - Map<String, Set<Hecho>> hechos = new HashMap<>()
    + saveAll(UUID coleccionID, Set<Hecho> setHechos)
    + Set<Hecho> findAll()
    + Set<Hecho> findAll(String coleccionID)
    + clear(String coleccionID)
    + clear()
    + Optional<Set<Hecho>> buscarPorTitulo(String titulo)
    + Optional<Set<Hecho>> findByColeccion(String idColeccion)
}

'SERVICIES
class HechoService {
    - IHechosDAO hechosDAO;
    - IHechoRepository hechosRepository;
    - HechoRepository hechoRepository;
    + ColeccionHecho importarDesdeCSV(MultipartFile archivo) throws IOException
    + Set<Hecho> obtenerTodos()
    + Optional<Set<Hecho>> buscarPorTitulo(String titulo)
    + Optional<Set<Hecho>> buscarPorColeccion(String idColeccion)
    + eliminarTodo()
}

'RELACIONES
HechoService --> IHechosDAO
HechoService --> IHechoRepository
HechoService --> HechoRepository
HechoService ..> ColeccionHecho
HechoService ..> Hecho

ColeccionHecho *-- Hecho

Hecho --> ColeccionHecho
Hecho --> Categoria
Hecho --> Ubicacion
Hecho --> Origen
Hecho ..> HechoValueObject

HechoValueObject --> Categoria
HechoValueObject --> Ubicacion

HechoGlobalController --> HechoRepository
HechoGlobalController ..> Hecho

ColeccionHechoController --> HechoService
ColeccionHechoController ..> Hecho


IHechosDAO <|.. DAOHechosCSV
IHechosDAO --> HechoValueObject

DAOHechosCSV --> HechoCSV

@enduml