@startuml
'https://plantuml.com/class-diagram

entity usuario {
    * id INTEGER(11) <<PK>>
    --
    * nombre VARCHAR(255)
    * fecha_nacimiento DATETIME
    * apellido VARCHAR(255)
    * email VARCHAR(255)
    * apellido VARCHAR(255)
    * rol VARCHAR(255)
}

entity permisos_usuario {
    * usuario_id INTEGER(11) <<FK>>
    --
    * nombre VARCHAR(255)
}

@enduml