@startuml
'https://plantuml.com/deployment-diagram

actor visualizador
actor administrador
actor contribuyente
component InstanciaMetaMapa
component APICatedra


frame Metamapa {
    node servicioAgregador {
    component APIAdministrador
    component APIVisualizador
    component APIService
    }
    visualizador "API REST" -(0- APIVisualizador
    administrador "API REST" -(0- APIAdministrador
    APIAdministrador -(0- APIService
    APIVisualizador -(0- APIService


    node servicioFuenteDinamica {
        component APIFuenteDinamica
        database Hechos {
        }
    }



    contribuyente "API REST" -(0- APIFuenteDinamica

    node servicioFuenteEstatica {
    component APIFuenteEstatica
    }



    node servicioFuenteProxy {
    component APIFuenteProxy
    }

    APIService "API REST" -(0- APIFuenteDinamica
        APIService "API REST" -(0- APIFuenteEstatica
        APIService  "API REST" -(0- APIFuenteProxy

    APIFuenteProxy "API REST" -(0- InstanciaMetaMapa
    APIFuenteProxy "API REST" -(0- APICatedra

    node servicioEstadistica {
        component APIEstadistica
    }

    administrador "API REST" -(0- APIEstadistica
    APIEstadistica "API REST" -(0- APIAdministrador
}




@enduml